//  Copyright (c) 2026, Ben McCart
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.

#ifndef FUZZY_LIB_ALL_HPP
#define FUZZY_LIB_ALL_HPP

#include <fuzzy/aggregator.hpp>
#include <fuzzy/algorithm.hpp>
#include <fuzzy/concepts.hpp>
#include <fuzzy/consequent.hpp>
#include <fuzzy/defuzzification.hpp>
#include <fuzzy/element.hpp>
#include <fuzzy/expressions.hpp>
#include <fuzzy/mapping_rule.hpp>
#include <fuzzy/math.hpp>
#include <fuzzy/norm_conorm.hpp>
#include <fuzzy/relation.hpp>
#include <fuzzy/set.hpp>
#include <fuzzy/scaled_antecedent.hpp>
#include <fuzzy/scaling_inference.hpp>
#include <fuzzy/scaled_mapping.hpp>
#include <fuzzy/traits.hpp>

#endif