//  Copyright (c) 2025, Ben McCart
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.

#include <fuzzy/algorithm.hpp>
#include <fuzzy/consequent.hpp>
#include <fuzzy/fwd.hpp>
#include <fuzzy/norm_conorm.hpp>
#include <fuzzy/set.hpp>

#ifndef FUZZY_AGGREGATOR_HPP
#define FUZZY_AGGREGATOR_HPP

namespace fuzzy
{


	/** 
	* Models the fuzzy basic_aggregator of a fuzzy antecedant, namely a fuzzy mapping_rule.	
	*/
	template <class V, class M, template <typename> class AggregatorFunc, template <typename T, typename Alloc = std::allocator<T>> class Container, class Allocator>
	requires fuzzy::numeric<V> && std::floating_point<M>
	class basic_aggregator
	{
	public:
		using set_type = basic_set<V, M, Container, Allocator>;
		using consequent_type = consequent<V,M,AggregatorFunc, Container, Allocator>;

		consequent_type shall_be(set_type&&) = delete;

		constexpr basic_aggregator(AggregatorFunc<M> func, Allocator alloc = Allocator()) : set_(alloc), func_(func) {}
		constexpr basic_aggregator(Allocator alloc = Allocator()) : set_(alloc) {}

		constexpr void aggregate(set_type const&);
		constexpr consequent_type shall_be(set_type const&) noexcept;
		constexpr set_type& result() noexcept;

	private:
		set_type set_;
		AggregatorFunc<M> func_;
		M scale_ = static_cast<M>(1);
		bool dirty_ = false;
	};
		

	/**
	* Template deduction guid for basic_aggregator.
	*/
	template <class V, class M, template <typename> class AggregatorFunc, template <typename T, typename Alloc = std::allocator<T>> class Container, class Allocator>
	requires fuzzy::numeric<V> && std::floating_point<M>
	basic_aggregator(basic_set<V, M, Container> const&, AggregatorFunc<M>, Allocator const& = Allocator()) -> basic_aggregator<V, M, AggregatorFunc, Container, Allocator>;

	/**
	* Aggregates the specified input to the basic_aggregator set.
	* @param input The input set  to aggregate (oputput from mapping_rule.)
	*/
	template <class V, class M, template <typename> class AggregatorFunc, template <typename T, typename Alloc = std::allocator<T>> class Container, class Allocator>
	requires fuzzy::numeric<V> && std::floating_point<M>
	constexpr void basic_aggregator<V, M, AggregatorFunc, Container, Allocator>::aggregate(set_type const& input)
	{
		using element_t = typename set_type::element_type;
		using pair_t = std::pair<element_t, element_t>;

		if (!dirty_)
		{
			std::for_each(set_.begin(), set_.end(), [&](element_t& e) -> void { e.membership(e.membership() * scale_); });
			dirty_ = true;
		}

		set_type result;
		detail::set_operation_value_sequence<V, M, Container> seq{ set_, input };
		for (pair_t const& pair : seq)
		{
			result.insert(element_t{ pair.first.value(), func_(pair.first.membership(), pair.second.membership()) });
		}
		set_.swap(result);
		dirty_ = true;
	}


	template <class V, class M, template <typename> class AggregatorFunc, template <typename T, typename Alloc = std::allocator<T>> class Container, class Allocator>
	requires fuzzy::numeric<V>&& std::floating_point<M>
	constexpr typename basic_aggregator<V, M, AggregatorFunc, Container, Allocator>::consequent_type basic_aggregator<V, M, AggregatorFunc, Container, Allocator>::shall_be(set_type const& target) noexcept
	{
		return consequent_type{ *this, target };
	}

	

	/**
	* Retrieves the underlying basic_aggregator fuzzy set via an implicit conversion operator.
	*/
	template <class V, class M, template <typename> class AggregatorFunc, template <typename T, typename Alloc = std::allocator<T>> class Container, class Allocator>
	requires fuzzy::numeric<V> && std::floating_point<M>
	constexpr typename basic_aggregator<V, M, AggregatorFunc, Container, Allocator>::set_type& basic_aggregator<V, M, AggregatorFunc, Container, Allocator>::result() noexcept
	{
		if (dirty_)
		{
			auto itr = std::max_element(begin(set_), end(set_), [](auto l, auto r) { return l.membership() < r.membership(); });
			if (itr != end(set_))
			{
				M const max = itr->membership();
				scale_ = std::max(static_cast<M>(1), max);
				if (max > static_cast<M>(1))
				{
					for (auto& element : set_)
					{
						element.membership(element.membership() / max);
					}
				}
			}
			dirty_ = false;
		}

		return set_;
	}


	/**
	 * @brief An aggregator function object for use with basic_aggregator.
	 * @tparam M 
	*/
	template <class M>
	requires std::floating_point<M>
	struct additive_function
	{
		using membership_type = M;

		constexpr additive_function() = default;
		constexpr additive_function(M) {}
		[[nodiscard]] constexpr membership_type operator()(membership_type a, membership_type b) const noexcept
		{
			return a + b;
		}
	};

	/**
	 * @brief An aggregator function objectfor use with basic_aggregator that uses a T-conorm for aggregation.
	*/
	template <typename M, template <typename> class Tconorm>
	requires std::floating_point<M>&& fuzzy::tconorm_type<Tconorm<M>>
	class tconorm_converter
	{
	public:
		using membership_type = M;

		constexpr tconorm_converter() = default;
		constexpr tconorm_converter(Tconorm<M>) {}
		[[nodiscard]] constexpr membership_type operator()(membership_type a, membership_type b) const noexcept
		{
			return Tconorm<M>::apply(a, b);
		}
	};

	template <typename M, template <typename> class Tconorm>
	tconorm_converter(Tconorm<M>) -> tconorm_converter<M, Tconorm>;

	/** Convenience defintion for common use cases. */
	using int_additive_aggregator = basic_aggregator<int, float, additive_function>;
	using additive_aggregator = basic_aggregator<float, float, additive_function>;

	template <typename M>
	using maximum_function = tconorm_converter<M, fuzzy::maximum>;
	using int_maximum_aggregator = basic_aggregator<int, float, maximum_function>;
	using maximum_aggregator = basic_aggregator<float, float, maximum_function>;
}


#endif // FUZZY_AGGREGATOR_HPP